# GitHub Actions workflow for Certification environment
name: Frontend Certification CI/CD

on:
  push:
    branches:
      - certification
  workflow_dispatch:

env:
  NODE_ENV: certification

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test -- --watch=false --browsers=ChromeHeadless
      
      - name: Build for certification
        run: npm run build:cert
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cert-build
          path: dist/
